


== Funkcije

Ni potrebno, da so del classov

[source,kotlin]
----
package com.demo.kotlin
import kotlin.io.println

fun main(args: Array<String>) {
    println("I'm Luna, a lvl 22 human adventurer")
}
----

[NOTE.speaker]
--
* static import
--


== !
[quote,John Carmack]
Sometimes, the elegant implementation is just a function.  Not a method.  Not a class.  Not a framework.  Just a function.


== Funkcije

Standardna knjižnjica jih je polna

[source,kotlin]
----
include::{sourcedir}/functions.kt[tag=useful1]
----


== Funkcije

Lahko vračajo več kot eno vrednost

[source,kotlin]
----
include::{sourcedir}/functions.kt[tag=multiple_return]
----




== Funkcije

Lahko si shranimo referenco na njih

[source,kotlin]
----
include::{sourcedir}/functions.kt[tag=pass_around]
----



== Funkcije

Lahko jih uporabimo kot tip argumenta..

[source,kotlin]
----
include::{sourcedir}/functions.kt[tag=parametrize]
----

..in si naredimo alias, ko postanejo podpisi predolgi

[source,kotlin]
----
include::{sourcedir}/functions.kt[tag=parametrize_alias]
----

== Funkcije

Lahko zahtevamo tip, na katerem se mora funkcija klicati

[source,kotlin]
----
include::{sourcedir}/functions.kt[tag=parametrize_with_receiver]
----

[NOTE.speaker]
--
* SAM v Javi + Kotlin interop!
* Statične metode s prvim parametrom
--


=== Primer: HTML Builder

[source,kotlin]
----
fun result(args: Array<String>) =
    html {
        head {
            title {+"XML encoding with Kotlin"}
        }
        body {
            h1 {+"XML encoding with Kotlin"}
            p  {
                +"This format can be used for XML markup; "
                +"it is totaly valid "
                a(href = "http://kotlinlang.org") {+"Kotlin"}
                +" code"
            }
        }
    }
}
----

===  Primer: HTML Builder

[source,kotlin]
----
class HTML : TagWithText("html") {
    fun head(init: Head.() -> Unit) = initTag(Head(), init)

    fun body(init: Body.() -> Unit) = initTag(Body(), init)
}

fun html(init: HTML.() -> Unit): HTML {
    val html = HTML()
    html.init()
    return html
}
----
(in tako naprej..)

[NOTE.speaker]
--
* Anko za Android
--


== Funkcije

Lahko razširimo obstoječe tipe, ne da bi jim popravili source

[source,kotlin]
----
package my.extensions

fun String.capitalize(): String {
    return if (isNotEmpty() && this[0].isLowerCase()) {
        substring(0, 1).toUpperCase() + substring(1)
    } else this
}
----

[source,kotlin]
----
import my.extensions.capitalize

fun main(args: Array<String>) {
    assert("luna".capitalize() == "Luna")
}
----

[NOTE.speaker]
--
* ogromno featurjev implementiranih tako
* platform packs
--



== Funkcije

Shorthand notacija

[source,kotlin]
----
include::{sourcedir}/functions.kt[tag=shorthand]
----



== Funkcije

Argumente lahko podamo z imenom

[source,kotlin]
----
include::{sourcedir}/functions.kt[tag=named_params1]
----

[source,kotlin]
----
include::{sourcedir}/functions.kt[tag=named_params2]
----



== Funkcije

Argumentom lahko damo tudi default vrednost

[source,kotlin]
----
fun joinToString(
    separator: CharSequence = ", ", 
    prefix: CharSequence = "", 
    postfix: CharSequence = "", 
    limit: Int = -1, 
    truncated: CharSequence = "...", 
    transform: ((T) -> CharSequence)? = null
): String { .. }

assert(listOf("A", "B", "C").joinToString() == "A, B, C")
----

[NOTE.speaker]
--
Java interop, lahko naredimo overloade!
--



== Funkcije

Olajšave za Lambda notacijo

[source,kotlin]
----
include::{sourcedir}/functions.kt[tag=lambda_last_and_it]
----




== Funkcije

Repno rekurzivne funkcije

[source,kotlin]
----
tailrec fun findFixPoint(x: Double = 1.0): Double {
    return if (x == Math.cos(x)) {
        x 
    } else {
        findFixPoint(Math.cos(x))
    }
}
----



== Korutine

//https://www.youtube.com/watch?v=_hfBv0a09Jc

[source,kotlin]
----
suspend fun fetchFortuneCookie(url: URL): String { .. }
async {
    println("Aaaand your fortune is...")
    val cookie = fetchFortuneCookie("http://api.fortunecookie.com")
    println(cookie)
}
----
(language feature, neodvisen od OS-a ali VM-ja)

[NOTE.speaker]
--
* Point? Preprostost (multithreaded je zajeban) in učinkovitost (ne blockajo)
* Lahko jih kličeš samo iz drugih suspend funkcij
* kontekst se shrani, nadaljuje pa lahko drug thread
--

=== Omogočajo

* Generatorje
* Async/Await
* Future & Promise
* Goroutine/Channel


=== !

V standardni knjižnjici Kotlin ponuja zgolj low level primitive, uporabnik pa se lahko odloči med različnimi implementacijami.
JetBrains ponuja naslednje:

 * kotlinx-coroutines-core
 * kotlinx-coroutines-jdk8
 * kotlinx-coroutines-nio
 * kotlinx-coroutines-android 
 * kotlinx-coroutines-javafx
 * kotlinx-coroutines-rx
 * kotlinx-coroutines-rx2

[NOTE.speaker]
--
Vse te implementacije so za JVM, obstaja pa korio, ki podpira tudi JS
Trenutno ne pridobiš toliko, ker so npr. RX knjižnjice odlične..
--


=== !

Primer: UI thread preservation

[source,kotlin]
----
textView.onClick {
    val r1 = bg { fetchResult1() }
    val r2 = bg { fetchResult2() }
    updateUI(r1.await(), r2.await())
}
----
 
 
=== !

Primer: generator

[source,kotlin]
----
val fibonacciSeq = buildSequence {
    var a = 0
    var b = 1

    yield(1)

    while (true) {
        yield(a + b)

        val tmp = a + b
        a = b
        b = tmp
    }
}
----






//== Funkcije
//
//Imajo več vrst dostopnosti
//
//[source,kotlin]
//----
//include::{sourcedir}/functions.kt[tag=visibility]
//----
//
//== Moduli
//
//A module is a set of Kotlin files compiled together:
//
//* an IntelliJ IDEA module;
//* a Maven project;
//* a Gradle source set;
//* a set of files compiled with one invocation of the Ant task












// external
